### ISSUE TITLE
Consider free-times when calculating total-time of a day

### ISSUE THREAD

**Issue by sneps85** [LukasVice/timeweb-genie#4]
Free-times (like Zeitausgleich, Urlaub, etc) should be subtracted from the total time (7,5h) to show correct Diff (Hours).

For example:
Office from 07:30-12:33 but Zeitausgleich in the afternoon (2:30) should lead to a total time of 5:00 (7:30 - 2:30) leading to a working time of 5:03 with Diff Hours 3m and Diff 0.05.

**Comment by sneps85** [comment]
The free-time could also be displayed in an additional column

**Comment by lukasvice** [comment]
I think all justification types that are not configured as working-time (like Smart Working or Telearbeit) should be considered as free-time. As you suggested, this could be displayed in a new column and included in the difference.
