### ISSUE TITLE
Falsche Abrechnung der Giustificativi "Zeitausgleich"

### ISSUE THREAD

**Issue by samuelru** [LukasVice/timeweb-genie#5]
Von mir aus werden jetzt mit der neuesten Version die Giustificativi vom Typ "Zeitausgleich" falsch abgerechnet. Dadurch, dass "Zeitausgleich" die Überstunden vom aktuellen Monat verbraucht und im Gegensatz zu "Freistunden" kein separater Deckel an Stunden aufgebraucht wird, muss von mir aus "Zeitausgleich" für die Berechnung ignoriert werden.

**Comment by lukasvice** [comment]
I am sorry, but I cannot continue to maintain this project. Please fork it and adapt it to your needs.
